name: ai-affiliate-marketing-system
services:
  - name: web
    type: web
    git:
      branch: main
    build:
      command: npm run build
    run:
      command: npm start
    ports:
      - port: 3000
        protocol: http
    env:
      - key: NODE_ENV
        value: production
    instance_type: nano
    regions:
      - fra
    scaling:
      min: 1
      max: 1